import { BadgeCheck, ChevronRight, Filter, MapPin, Mountain, Phone, Search, X } from "lucide-react";
import { useMemo, useState } from "react";
import { InstallAppButton } from "@/components/InstallAppButton";
import approvedProviders from "@/data/providers.json";

const FORM_URL = "https://docs.google.com/forms/d/1yhRwoAGxL2NNcBiK5UudcHBE7oFZy1ahld-_iannbP4/viewform";
const towns = ["Todos los pueblos", "Aibonito", "Barranquitas", "Comerío", "Corozal", "Naranjito", "Orocovis"];

type ProviderCard = {
  id: number; businessName: string; phone: string; whatsapp: string | null;
  description: string | null; primaryCategory: string; serviceTags: string[];
  town?: string; coverageTowns?: string[];
};
const providers: ProviderCard[] = approvedProviders;
const hasLocation = providers.length > 0 && providers.every(item => Boolean(item.town));
const categories = ["Todas las categorías", ...new Set(providers.map(item => item.primaryCategory))];

function QualityBadge() {
  return <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700"><BadgeCheck className="h-3.5 w-3.5" />Datos confirmados</span>;
}
function Location({ provider }: { provider: ProviderCard }) {
  if (!hasLocation || !provider.town) return null;
  return <div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><MapPin className="h-4 w-4 text-[#bd8f2c]" /><span>{provider.town}{provider.coverageTowns?.length ? ` · Atiende ${provider.coverageTowns.join(", ")}` : ""}</span></div>;
}
function ProviderCardView({ provider, onOpen }: { provider: ProviderCard; onOpen: () => void }) {
  return <article className="group relative overflow-hidden rounded-[1.45rem] border border-slate-200 bg-white p-5 shadow-[0_18px_40px_-30px_rgba(29,49,84,0.55)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_22px_42px_-24px_rgba(29,49,84,0.32)]">
    <div className="flex items-start justify-between gap-3 pt-1"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#52677d]">{provider.primaryCategory}</p><h3 className="mt-1 text-lg font-bold tracking-tight text-[#162b4a]">{provider.businessName}</h3><p className="mt-1 text-sm text-slate-500">Proveedor local</p></div><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#edf1f4] font-serif text-xl font-bold text-[#1d3154]">{provider.businessName.slice(0, 1)}</div></div>
    <div className="mt-4 flex flex-wrap gap-2"><QualityBadge /></div>
    <p className="mt-4 min-h-10 text-sm leading-6 text-slate-600">{provider.description || `Servicios de ${provider.primaryCategory.toLocaleLowerCase("es-PR")} en el área central.`}</p>
    <div className="mt-4 flex flex-wrap gap-1.5">{provider.serviceTags.slice(0, 4).map(tag => <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600" key={tag}>{tag}</span>)}</div>
    <Location provider={provider} />
    <button type="button" onClick={onOpen} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#1d3154] transition hover:gap-2">Ver ficha <ChevronRight className="h-4 w-4" /></button>
  </article>;
}

export default function PublicDirectory() {
  const [query, setQuery] = useState("");
  const [town, setTown] = useState("Todos los pueblos");
  const [category, setCategory] = useState("Todas las categorías");
  const [selected, setSelected] = useState<ProviderCard | null>(null);
  const results = useMemo(() => providers.filter(provider => {
    const q = query.trim().toLocaleLowerCase("es-PR");
    const searchable = [provider.businessName, provider.primaryCategory, provider.description ?? "", ...provider.serviceTags].join(" ").toLocaleLowerCase("es-PR");
    return (!q || searchable.includes(q)) && (category === "Todas las categorías" || provider.primaryCategory === category)
      && (!hasLocation || town === "Todos los pueblos" || provider.town === town || provider.coverageTowns?.includes(town) || provider.coverageTowns?.includes("Todo el área"));
  }), [query, category, town]);

  return <div className="min-h-screen bg-[#fbfaf7] font-['DM_Sans'] text-slate-800">
    <header className="border-b border-slate-200/80 bg-[#fbfaf7]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-2 px-3 py-4 sm:gap-4 sm:px-8"><a href="/" className="flex min-w-0 items-center gap-2 sm:gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[#1d3154] text-[#f2cd57] shadow-sm"><Mountain className="h-5 w-5" /></span><span><strong className="block text-[13px] tracking-tight text-[#162b4a] sm:text-[15px]">La Montaña Resuelve</strong><small className="block text-xs text-slate-500">Directorio del área central</small></span></a><div className="flex shrink-0 items-center gap-2"><InstallAppButton compact /><a href={FORM_URL} className="rounded-full bg-[#1d3154] px-3 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-[#294269] active:scale-[0.97] sm:px-4"><span className="sm:hidden">Registrar</span><span className="hidden sm:inline">Registrar mi negocio</span></a></div></div></header>
    <main>
      <section className="relative overflow-hidden bg-[#1d3154] px-5 pb-16 pt-14 text-white sm:px-8"><div className="absolute right-[-7rem] top-[-8rem] h-72 w-72 rounded-full border-[28px] border-[#f2cd57]/20" /><svg aria-hidden="true" className="absolute bottom-0 right-0 h-56 w-[48rem] max-w-[90vw] text-[#f2cd57]/15" viewBox="0 0 780 220" fill="none"><path d="M0 185C78 118 124 164 195 102C262 44 335 144 402 82C459 29 541 95 592 56C645 15 724 43 780 0" stroke="currentColor" strokeWidth="2" /><path d="M0 211C78 144 125 190 197 128C262 72 335 170 404 108C461 56 543 122 595 82C648 41 727 69 780 26" stroke="currentColor" strokeWidth="2" /><path d="M0 156C78 89 124 135 195 73C262 15 335 115 402 53C459 0 541 66 592 27C645 -14 724 14 780 -29" stroke="currentColor" strokeWidth="2" /></svg><div className="relative mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#f2cd57]">Conecta localmente</p><h1 className="mt-4 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Encuentra soluciones de confianza cerca de ti.</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-200">{hasLocation ? "Busca proveedores por pueblo y servicio." : "Busca proveedores por servicio."} Las etiquetas separan la actualización de los datos de cualquier nivel de visibilidad patrocinada.</p><div className={`mt-8 grid gap-3 rounded-[1.5rem] bg-white p-3 shadow-2xl ${hasLocation ? "sm:grid-cols-[1.6fr_1fr_1fr_auto]" : "sm:grid-cols-[1.6fr_1fr_auto]"}`}><label className="flex items-center gap-2 rounded-xl bg-slate-50 px-3"><Search className="h-5 w-5 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="¿Qué servicio necesitas?" aria-label="Buscar servicio" className="h-12 w-full bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400" /></label>{hasLocation ? <select value={town} onChange={event => setTown(event.target.value)} aria-label="Pueblo" className="h-12 rounded-xl bg-slate-50 px-3 text-sm font-medium text-slate-700 outline-none">{towns.map(item => <option key={item}>{item}</option>)}</select> : null}<select value={category} onChange={event => setCategory(event.target.value)} aria-label="Categoría" className="h-12 rounded-xl bg-slate-50 px-3 text-sm font-medium text-slate-700 outline-none">{categories.map(item => <option key={item}>{item}</option>)}</select><button type="button" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#f2cd57] px-4 text-sm font-bold text-[#1d3154] active:scale-[0.97]"><Filter className="h-4 w-4" />Filtrar</button></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#bd8f2c]">Directorio público</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-[#162b4a]">Proveedores del área central</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">“Datos confirmados” indica que la información de la ficha fue confirmada directamente con el proveedor y aprobada para publicación. La visibilidad patrocinada no indica calidad del servicio.</p></div>{results.length > 0 ? <div className="mt-10"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-bold text-[#162b4a]">Todas las opciones</h3><span className="text-sm text-slate-500">{results.length} resultado{results.length === 1 ? "" : "s"}</span></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{results.map(provider => <ProviderCardView key={provider.id} provider={provider} onOpen={() => setSelected(provider)} />)}</div></div> : <div className="rounded-[1.5rem] border border-dashed border-[#c7d1da] bg-white px-6 py-14 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#edf1f4]"><Search className="h-6 w-6 text-[#52677d]" /></div><h3 className="mt-5 text-xl font-bold text-[#162b4a]">Aún no hay fichas que coincidan</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">La nueva versión no copia datos sin confirmación. El propietario revisa y aprueba cada ficha antes de mostrarla aquí.</p></div>}</section>
    </main>
    {selected ? <div className="fixed inset-0 z-50 flex items-end bg-[#142641]/50 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6"><div role="dialog" aria-modal="true" aria-label={`Ficha de ${selected.businessName}`} className="max-h-[90vh] w-full overflow-y-auto rounded-t-[2rem] bg-[#fbfaf7] p-6 shadow-2xl sm:max-w-xl sm:rounded-[2rem]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#bd8f2c]">{selected.primaryCategory}</p><h2 className="mt-1 text-2xl font-bold text-[#162b4a]">{selected.businessName}</h2><p className="mt-1 text-sm text-slate-500">Proveedor local</p></div><button type="button" onClick={() => setSelected(null)} aria-label="Cerrar" className="rounded-full p-2 text-slate-500 hover:bg-slate-200"><X className="h-5 w-5" /></button></div><div className="mt-4 flex flex-wrap gap-2"><QualityBadge /></div><p className="mt-5 leading-7 text-slate-600">{selected.description || "Información de servicios pendiente de completar."}</p><div className="mt-5 rounded-2xl bg-white p-4"><p className="text-sm font-bold text-[#162b4a]">Servicios</p><p className="mt-1 text-sm leading-6 text-slate-600">{selected.serviceTags.join(" · ")}</p><Location provider={selected} /></div><div className="mt-5 grid grid-cols-2 gap-3"><a href={`tel:${selected.phone.replace(/\D/g, "")}`} className="flex items-center justify-center gap-2 rounded-xl bg-[#1d3154] px-4 py-3 font-bold text-white"><Phone className="h-4 w-4" />Llamar</a>{selected.whatsapp ? <a href={`https://wa.me/${selected.whatsapp.replace(/\D/g, "")}?text=${encodeURIComponent(`Hola, vi ${selected.businessName} en La Montaña Resuelve.`)}`} target="_blank" rel="noreferrer" className="flex items-center justify-center rounded-xl bg-[#18864b] px-4 py-3 font-bold text-white">WhatsApp</a> : <span className="rounded-xl bg-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-500">WhatsApp no indicado</span>}</div></div></div> : null}
  </div>;
}
